# utilisation du registre d'image privé de gitlab
# procédure: 
## docker login gitlab.myusine.fr:5050 (root/roottoor)
## docker tag node:lts-buster-slim gitlab.myusine.fr:5050/myusine/dev/node:lts-buster-slim
## docker push gitlab.myusine.fr:5050/myusine/dev/node:lts-buster-slim
image: gitlab.myusine.fr:5050/myusine/dev/node:lts-buster-slim

test:
  tags: [myusine]
  script: 
    - node -v
