image: $CI_REGISTRY_IMAGE/node:lts-buster-slim

# règles d'exécution du pipeline
workflow:
  # le pipeline s'exécute si au moins une règle est vraie
  # OU logique
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  

stages:
  - testing
  - building
  - deploying

test:
  stage: testing
  tags: [myusine]
  script: 
    - node -v

build:
  stage: building
  tags: [myusine]
  script: 
    - npm list -g


deploy:
  stage: deploying
  tags: [myusine]
  script: 
    - echo "deploy !!"

