image: $CI_REGISTRY_IMAGE/node:lts-buster-slim

stages:
  - testing
  - building
  - deploying

test:
  # un job appartient à un stage, cela fixe son ordre d'exécution
  stage: testing
  tags: [myusine]
  script: 
    - node -v

build:
  stage: building
  tags: [myusine]
  script: 
    - npm list -g


deploy:
  stage: deploying
  tags: [myusine]
  script: 
    - echo "deploy !!"

