image: $CI_REGISTRY_IMAGE/node:lts-buster-slim

stages:
  - testing
  - building
  - deploying

test:
  # un job appartient à un stage, cela fixe son ordre d'exécution
  stage: testing
  tags: [myusine]
  script: 
    - node -v

build:
  stage: building
  # dépendance stricte au job test => build démarre dès après job,
  # avant la fin du stage testing
  needs: [test]
  tags: [myusine]
  script: 
    - npm list -g

# appel à la CI/CD du projet myusine/ops
# pipeline multi projet
trigger_ops:
  stage: deploying
  trigger:
    project: myusine/ops
    branch: main
    

