# image par défaut pour tous les jobs du pipeline
# l'image est téléchargée depuis hub.docker.com
# nomenclature: nom_image:nom_tag
# l'image décrit la techno
# le tag décrit la distrib socle et/ou la version
image: node:lts-buster-slim

test:
  tags: [myusine]
  script: 
    - node -v
