image: $CI_REGISTRY_IMAGE/node:lts-buster-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  
stages:
  - testing
  - building
  - deploying

test:
  # bonne solution: utilisation d'une image contenant déjà chrome
  # image spécifique au job
  image: $CI_REGISTRY_IMAGE/node-chrome:debian-node16
  stage: testing
  tags: [myusine]
  # mauvaise solution: installer chrome à chaque exécution du job
  # before_script:
  #   - apt-get update && apt-get install -y google-chrome-stable 
  script:
    - cd cicd_angular
    - npm install
    - npm run test:ci
  rules:
    - if: $CI_COMMIT_BRANCH =~ /[0-9]+(-[a-z]+)+/
    - if: $CI_COMMIT_BRANCH == "master"

build:
  stage: building
  tags: [myusine]
  script: 
    - npm list -g


deploy:
  stage: deploying
  tags: [myusine]
  script: 
    - echo "deploy !!"
  environment:
    name: prod
    url: https://dawan.fr
  rules:
    # on déploit si l'objet poussé est un tag
    - if: $CI_COMMIT_TAG
    # et si on appuie sur un bouton
      when: manual

